name: Test Workflow
on:
  workflow_dispatch:
    inputs:
      greeting:
        description: 'how do you say hello'
        required: true
        type: string

jobs:
  get-vars:
    environment: npe
    runs-on: ubuntu-latest
    outputs: 
      YOURMOM: ${{ steps.get-vars.outputs.YOURMOM }}
    steps:
      - name: Get Some Vars
        run: |
          echo "reading vars 1"
          echo "your mom: ${{ secrets.YOURMOM }}"

          YOURMOM="bork"
          echo "::set-output name=YOURMOM::$YOURMOM"

          # PROD = 1
          # NPE = 2
          if ${{ secrets.YOURMOM }} -eq "2"; then
            echo "ha it's 2"
          else
            echo "it is not 2"
          fi
          

  set-vars:
    environment: all
    runs-on: ubuntu-latest
    needs: get-vars
    steps:
      - name: Set Some Vars
        run: |
          echo "reading vars from all"
          echo "i don't know: ${{ secrets.IDONTKNOW }}"

          echo "reading vars passed from get-vars job"
          echo "your mom: ${{ needs.get-vars.outputs.YOURMOM }}"
