name: Test Workflow
on: [push, workflow_dispatch]

jobs:
  get-vars:
    environment: npe
    runs-on: ubuntu-latest
    outputs: 
      YOURMOM: ${{ steps.get-vars-step.outputs.YOURMOM }}
      YOURMOM2: ${{ steps.get-vars-step.outputs.YOURMOM2 }}
    steps:
      - name: get-vars-step
        id: get-vars-step
        run: |
          YOURMOM=${{ secrets.YOURMOM }}
          echo "::add-mask::$YOURMOM"
          echo "::set-output name=YOURMOM::$YOURMOM"

          YOURMOM2="borkasaurus"
          echo "::add-mask::$YOURMOM2"
          echo "::set-output name=YOURMOM2::$YOURMOM2"


      - name: hm
        run: |
          echo "echoing the secret: ${{ steps.get-vars-step.outputs.YOURMOM }}"

  set-vars:
    environment: all
    runs-on: ubuntu-latest
    needs: get-vars
    steps:
      - name: Set Some Vars
        run: |
          echo "reading vars from all"
          echo "i don't know: ${{ secrets.IDONTKNOW }}"

          echo "reading vars passed from get-vars job"
          echo "your mom: ${{ needs.get-vars.outputs.YOURMOM }}"

          echo "your mom 2: the borkening: ${{ needs.get-vars.outputs.YOURMOM2 }}"


          # PROD = 1
          # NPE = 2
          if [[ $YOURMOM == "2" ]]; then
            echo "matched! second number"
          else
            echo "no match, sadface - first number"
          fi
