name: Test Workflow
on:
  workflow_dispatch:
    inputs:
      greeting:
        description: 'how do you say hello'
        required: false
        type: string

jobs:
  get-vars:
    environment: npe
    runs-on: ubuntu-latest
    outputs: 
      YOURMOM: ${{ steps.get-vars-step.outputs.YOURMOM }}
    steps:
      - name: get-vars-step
        run: |
          # echo "reading vars 1"
          # echo "your mom: ${{ secrets.YOURMOM }}"

          YOURMOM="bork"
          echo "Your Mom: $YOURMOM"
          echo "::set-output name=YOURMOM::$YOURMOM"

          # PROD = 1
          # NPE = 2
          if [[ "$YOURMOM" == "bork" ]]; then
            echo "matched!"
          else
            echo "no match sadface"
            echo $YOURMOM
          fi
          

  set-vars:
    environment: all
    runs-on: ubuntu-latest
    needs: get-vars
    steps:
      - name: Set Some Vars
        run: |
          echo "reading vars from all"
          echo "i don't know: ${{ secrets.IDONTKNOW }}"

          echo "reading vars passed from get-vars job"
          echo "your mom: ${{ needs.get-vars.outputs.YOURMOM }}"
